name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 #v3.1.0
      - name: Build manifests
        run: make release-manifests
      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
        with:
          files: |
            _output/components.yaml
            _output/high-availability.yaml
            _output/high-availability-1.21+.yaml
